version: '3.8'

services:
  app:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      NODE_ENV: development
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: blog
      DB_USER: postgres
      DB_PASSWORD: postgres
    volumes:
      - ./src:/usr/src/app/src
      - ./dist:/usr/src/app/dist
      - ./node_modules:/usr/src/app/node_modules
    command: npm run dev

  db:
    image: postgres:14-alpine
    restart: always
    environment:
      POSTGRES_DB: blog
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: 